/*
 * generated by Xtext 2.22.0
 */
package at.ac.tuwien.big.cps.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CpsamlUiModule extends AbstractCpsamlUiModule {

	public CpsamlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
