/*
 * generated by Xtext 2.22.0
 */
package at.ac.tuwien.big.cps;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CpsamlStandaloneSetup extends CpsamlStandaloneSetupGenerated {

	public static void doSetup() {
		new CpsamlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
