/*
 * generated by Xtext 2.22.0
 */
package at.ac.tuwien.big.cps.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCpsamlScopeProvider extends DelegatingScopeProvider {
}
