/*
 * generated by Xtext 2.22.0
 */
package at.ac.tuwien.big.cps.parser.antlr;

import at.ac.tuwien.big.cps.parser.antlr.internal.InternalCpsamlParser;
import at.ac.tuwien.big.cps.services.CpsamlGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class CpsamlParser extends AbstractAntlrParser {

	@Inject
	private CpsamlGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_SL_COMMENT", "RULE_ML_COMMENT");
	}
	

	@Override
	protected InternalCpsamlParser createParser(XtextTokenStream stream) {
		return new InternalCpsamlParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "CpsSystem";
	}

	public CpsamlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CpsamlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
