/*
 * generated by Xtext 2.22.0
 */
package at.ac.tuwien.big.cps.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CpsamlAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("at/ac/tuwien/big/cps/parser/antlr/internal/InternalCpsaml.tokens");
	}
}
